services:
  - type: web
    name: whosnext
    runtime: node
    plan: free
    buildCommand: npm install && npm run build:renderer
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
